const seed = {
  users:{lizbeth:{name:'Lizbeth',role:'admin'},edgar:{name:'Edgar',role:'admin'},recepcion:{name:'Recepción',role:'reception'}},
  services:[
    {id:1,name:'Manicure con gel',price:30,duration:40},{id:2,name:'Pedicure spa',price:45,duration:90},{id:3,name:'Pedicure acripie',price:70,duration:120},{id:4,name:'Uñas acrílicas',price:55,duration:120},{id:5,name:'Relleno',price:45,duration:60},{id:6,name:'Diseño de uñas',price:10,duration:30},{id:7,name:'Retiro de acrílico',price:20,duration:30},{id:8,name:'Builder gel',price:40,duration:40},{id:9,name:'Extensiones de tape',price:100,duration:90},{id:10,name:'Extensiones de micro chip',price:150,duration:180},{id:11,name:'Faciales',price:80,duration:60},{id:12,name:'Wax',price:25,duration:20},{id:13,name:'Tratamiento de keratina',price:120,duration:120},{id:14,name:'Massage relajante',price:40,duration:30}
  ],
  clients:[
    {id:1,name:'María López',phone:'909-555-0101',instagram:'@marial',allergies:'Ninguna',favorite:'Uñas rojas',spent:420,visits:7},
    {id:2,name:'Ana Torres',phone:'909-555-0134',instagram:'@anatorres',allergies:'Alergia al látex',favorite:'Diseños florales',spent:280,visits:5},
    {id:3,name:'Sofía Ruiz',phone:'909-555-0168',instagram:'@sofiar',allergies:'Ninguna',favorite:'Keratina',spent:610,visits:8}
  ],
  appointments:[], payments:[], waitlist:[{name:'Carla Méndez',service:'Uñas acrílicas'}], settings:{theme:'light'}
};

const todayISO=()=>new Date().toISOString().slice(0,10);
function initialAppointments(){const d=todayISO();return [
 {id:1,client:'María López',service:'Manicure con gel',date:d,time:'09:00',status:'Confirmada',price:35},
 {id:2,client:'Ana Torres',service:'Pedicure spa',date:d,time:'11:00',status:'Pendiente',price:50},
 {id:3,client:'Sofía Ruiz',service:'Faciales',date:d,time:'14:30',status:'Confirmada',price:80}
]}
function loadData(){let data=JSON.parse(localStorage.getItem('artbeautyData')||'null');if(!data){data=structuredClone(seed);data.appointments=initialAppointments();localStorage.setItem('artbeautyData',JSON.stringify(data));}return data}
let data=loadData(), currentUser=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('artbeautyData',JSON.stringify(data));renderAll()}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function statusBadge(s){const c=s==='Confirmada'||s==='Completada'?'success':s==='Cancelada'?'danger':'warning';return `<span class="badge ${c}">${s}</span>`}

$('#loginBtn').onclick=()=>{const user=$('#loginUser').value,p=$('#loginPassword').value;if(p!=='1234')return toast('Contraseña incorrecta');currentUser=data.users[user];$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=currentUser.name;$('#userInitial').textContent=currentUser.name[0];$('#roleLabel').textContent=currentUser.role==='admin'?'Administración':'Modo Recepción';applyPermissions();renderAll();}
$('#loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
$('#logoutBtn').onclick=()=>location.reload();
$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
$$('#mainNav button,[data-go]').forEach(b=>b.onclick=()=>goPage(b.dataset.page||b.dataset.go));
function goPage(id){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');$$('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#pageTitle').textContent=$(`#mainNav button[data-page="${id}"]`)?.textContent||'ArtBeauty';$('.sidebar').classList.remove('open')}
function applyPermissions(){const rec=currentUser?.role==='reception';$$('.admin-only').forEach(el=>el.style.display=rec?'none':'');if(rec)goPage('reception')}

function renderAll(){renderDashboard();renderAppointments();renderClients();renderServices();renderPayments();renderReception();renderAI();}
function renderDashboard(){const todays=data.appointments.filter(a=>a.date===todayISO()&&a.status!=='Cancelada');const sales=data.payments.filter(p=>p.date===todayISO()).reduce((s,p)=>s+Number(p.total),0);$('#statAppointments').textContent=todays.length;$('#statSales').textContent=money(sales);$('#statVip').textContent=data.clients.filter(c=>c.spent>=400).length;$('#statWait').textContent=data.waitlist.length;$('#statNext').textContent=todays[0]?`Próxima: ${todays.sort((a,b)=>a.time.localeCompare(b.time))[0].time}`:'Sin próxima cita';$('#smartGreeting').textContent=`Buenos días, ${currentUser?.name||'Lizbeth'} 👋`;$('#smartSummary').textContent=`Hoy tienes ${todays.length} citas. Llevas ${money(sales)} en ventas registradas.`;$('#todayText').textContent=new Date().toLocaleDateString('es-MX',{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('#todayAppointments').innerHTML=todays.length?todays.map(a=>`<div class="list-item"><div><strong>${a.time} · ${a.client}</strong><small>${a.service}</small></div>${statusBadge(a.status)}</div>`).join(''):'<p class="muted">No hay citas para hoy.</p>';$('#alertsList').innerHTML=`<div class="list-item"><div><strong>${data.waitlist.length} clienta(s) en espera</strong><small>Contacta cuando se libere un espacio.</small></div><span>⏳</span></div><div class="list-item"><div><strong>Meta diaria</strong><small>Faltan ${money(Math.max(0,450-sales))} para llegar a $450.</small></div><span>🎯</span></div>`}
function filteredAppointments(){const q=$('#appointmentSearch').value.toLowerCase(),d=$('#appointmentDateFilter').value,s=$('#appointmentStatusFilter').value;return data.appointments.filter(a=>(!q||`${a.client} ${a.service}`.toLowerCase().includes(q))&&(!d||a.date===d)&&(!s||a.status===s))}
function renderAppointments(){const rows=filteredAppointments();$('#appointmentsTable').innerHTML=`<table class="data-table"><thead><tr><th>Fecha</th><th>Hora</th><th>Clienta</th><th>Servicio</th><th>Estado</th><th>Precio</th><th>Acción</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${a.date}</td><td>${a.time}</td><td>${a.client}</td><td>${a.service}</td><td>${statusBadge(a.status)}</td><td>${money(a.price)}</td><td><button class="secondary" onclick="changeStatus(${a.id})">Cambiar</button></td></tr>`).join('')||'<tr><td colspan="7">Sin resultados</td></tr>'}</tbody></table>`}
['appointmentSearch','appointmentDateFilter','appointmentStatusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderAppointments));
window.changeStatus=id=>{const a=data.appointments.find(x=>x.id===id);const states=['Pendiente','Confirmada','En servicio','Completada','Cancelada'];a.status=states[(states.indexOf(a.status)+1)%states.length];save()}
function renderClients(){const q=$('#clientSearch').value.toLowerCase();const list=data.clients.filter(c=>!q||`${c.name} ${c.phone} ${c.instagram}`.toLowerCase().includes(q));$('#clientsGrid').innerHTML=list.map(c=>`<article class="client-card"><div class="card-avatar">${c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h4>${c.name}</h4><div class="muted">${c.phone}<br>${c.instagram||''}</div><div class="card-meta"><span>${c.visits} visitas</span><strong>${money(c.spent)}</strong></div><p><small><b>Preferencia:</b> ${c.favorite}<br><b>Alergias:</b> ${c.allergies}</small></p></article>`).join('')}
$('#clientSearch').addEventListener('input',renderClients);
function renderServices(){$('#servicesGrid').innerHTML=data.services.map(s=>`<article class="service-card"><span class="badge">${s.duration} min</span><h4>${s.name}</h4><p class="muted">Precio base</p><strong>${money(s.price)}+</strong></article>`).join('')}
function renderPayments(){const total=data.payments.reduce((s,p)=>s+Number(p.total),0),tips=data.payments.reduce((s,p)=>s+Number(p.tip||0),0),bal=data.payments.reduce((s,p)=>s+Number(p.balance||0),0);$('#paymentTotal').textContent=money(total);$('#tipTotal').textContent=money(tips);$('#balanceTotal').textContent=money(bal);$('#paymentsTable').innerHTML=`<table class="data-table"><thead><tr><th>Fecha</th><th>Clienta</th><th>Método</th><th>Total</th><th>Propina</th><th>Saldo</th></tr></thead><tbody>${data.payments.map(p=>`<tr><td>${p.date}</td><td>${p.client}</td><td>${p.method}</td><td>${money(p.total)}</td><td>${money(p.tip)}</td><td>${money(p.balance)}</td></tr>`).join('')||'<tr><td colspan="6">Todavía no hay pagos registrados.</td></tr>'}</tbody></table>`}
function renderReception(){const next=data.appointments.filter(a=>a.date>=todayISO()&&a.status!=='Cancelada').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5);$('#receptionAppointments').innerHTML=next.map(a=>`<div class="list-item"><div><strong>${a.date} · ${a.time}</strong><small>${a.client} — ${a.service}</small></div>${statusBadge(a.status)}</div>`).join('')}
function renderAI(){const sales=data.payments.reduce((s,p)=>s+Number(p.total),0);const top=[...data.services].sort((a,b)=>b.price-a.price)[0];$('#aiRecommendations').innerHTML=`<div class="list-item"><div><strong>Seguimiento de clientas</strong><small>${data.clients.length} perfiles disponibles para campañas.</small></div><span>💬</span></div><div class="list-item"><div><strong>Potencial de ventas</strong><small>${top.name} es uno de los servicios con mayor precio base.</small></div><span>📈</span></div><div class="list-item"><div><strong>Ventas acumuladas</strong><small>${money(sales)} registrados en esta versión demo.</small></div><span>💰</span></div>`}

function openModal(title,html,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal();$('#modalForm').onsubmit=e=>{e.preventDefault();onSave(new FormData(e.target));$('#modal').close();save();toast('Guardado correctamente')}}
function appointmentModal(){openModal('Nueva cita',`<label>Clienta<select name="client">${data.clients.map(c=>`<option>${c.name}</option>`)}</select></label><label>Servicio<select name="service">${data.services.map(s=>`<option value="${s.name}">${s.name}</option>`).join('')}</select></label><label>Fecha<input name="date" type="date" value="${todayISO()}" required></label><label>Hora<input name="time" type="time" required></label><label>Estado<select name="status"><option>Pendiente</option><option>Confirmada</option></select></label><label>Precio<input name="price" type="number" min="0" value="30"></label>`,fd=>data.appointments.push({id:Date.now(),client:fd.get('client'),service:fd.get('service'),date:fd.get('date'),time:fd.get('time'),status:fd.get('status'),price:+fd.get('price')}))}
function clientModal(){openModal('Nueva clienta',`<label>Nombre<input name="name" required></label><label>Teléfono<input name="phone" required></label><label>Instagram<input name="instagram"></label><label>Alergias<input name="allergies" value="Ninguna"></label><label class="wide">Preferencias<textarea name="favorite"></textarea></label>`,fd=>data.clients.push({id:Date.now(),name:fd.get('name'),phone:fd.get('phone'),instagram:fd.get('instagram'),allergies:fd.get('allergies'),favorite:fd.get('favorite'),spent:0,visits:0}))}
function serviceModal(){openModal('Nuevo servicio',`<label>Servicio<input name="name" required></label><label>Precio base<input name="price" type="number" min="0" required></label><label>Duración (minutos)<input name="duration" type="number" min="10" required></label>`,fd=>data.services.push({id:Date.now(),name:fd.get('name'),price:+fd.get('price'),duration:+fd.get('duration')}))}
function paymentModal(){openModal('Registrar pago',`<label>Clienta<select name="client">${data.clients.map(c=>`<option>${c.name}</option>`)}</select></label><label>Fecha<input name="date" type="date" value="${todayISO()}"></label><label>Método<select name="method"><option>Efectivo</option><option>Zelle</option><option>Tarjeta</option></select></label><label>Total<input name="total" type="number" min="0" required></label><label>Propina<input name="tip" type="number" min="0" value="0"></label><label>Saldo pendiente<input name="balance" type="number" min="0" value="0"></label>`,fd=>data.payments.push({id:Date.now(),client:fd.get('client'),date:fd.get('date'),method:fd.get('method'),total:+fd.get('total'),tip:+fd.get('tip'),balance:+fd.get('balance')}))}
$('#newAppointmentBtn').onclick=$('#receptionNewAppointment').onclick=appointmentModal;$('#newClientBtn').onclick=clientModal;$('#newServiceBtn').onclick=serviceModal;$('#newPaymentBtn').onclick=$('#receptionPayment').onclick=paymentModal;
$('#receptionCheckIn').onclick=()=>{const a=data.appointments.find(x=>x.date===todayISO()&&x.status!=='Cancelada'&&x.status!=='Completada');if(!a)return toast('No hay citas pendientes');a.status='En servicio';save();toast(`${a.client} marcada como presente`)}
function aiReply(q){q=q.toLowerCase();if(q.includes('vend'))return `Las ventas registradas suman ${money(data.payments.reduce((s,p)=>s+Number(p.total),0))}.`;if(q.includes('cita'))return `Tienes ${data.appointments.filter(a=>a.date===todayISO()&&a.status!=='Cancelada').length} citas programadas para hoy.`;if(q.includes('servicio')){const count={};data.appointments.forEach(a=>count[a.service]=(count[a.service]||0)+1);const top=Object.entries(count).sort((a,b)=>b[1]-a[1])[0];return top?`El servicio más reservado es ${top[0]}, con ${top[1]} cita(s).`:'Todavía no hay suficientes citas para calcularlo.'}if(q.includes('vip')||q.includes('mejor'))return `Hay ${data.clients.filter(c=>c.spent>=400).length} clientas VIP según su gasto acumulado.`;return 'Puedo ayudarte con ventas, citas, servicios y clientas VIP. Esta primera versión usa los datos guardados en tu dispositivo.'}
function sendAI(text){if(!text.trim())return;$('#aiMessages').insertAdjacentHTML('beforeend',`<div class="message user">${text}</div><div class="message bot">${aiReply(text)}</div>`);$('#aiInput').value='';$('#aiMessages').scrollTop=$('#aiMessages').scrollHeight}
$('#aiSend').onclick=()=>sendAI($('#aiInput').value);$('#aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAI(e.target.value)});$$('.quick-prompts button').forEach(b=>b.onclick=()=>sendAI(b.textContent));
$('#themeSelect').onchange=e=>document.body.classList.toggle('dark',e.target.value==='dark');$('#saveSettingsBtn').onclick=()=>toast('Configuración guardada');
